run: main.cpp
	g++ -std=c++11  main.cpp -o ____ -Wformat=0 -Wpointer-arith -lm
dbg: main.cpp
	g++ -DDEBUG=0 -std=c++11  main.cpp -g -o ____ -Wformat=0 -Wpointer-arith -lm
DBG: main.cpp
	g++ -DDEBUG=1 -std=c++11  main.cpp -g -o ____ -Wformat=0 -Wpointer-arith -lm
# default: main

# HEADERS_MAIN = ReaderFiles/ClassLoader.hpp ClassFileStructures/ClassFile.hpp ViewerFiles/Exibidor.hpp VMGlobals.hpp

# main:	main.o
# 	g++ main.o -o main
